package com.revrank.presentation.screens.onboarding

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.revrank.R
import com.revrank.presentation.components.RevRankButton
import com.revrank.presentation.theme.Danger
import com.revrank.presentation.theme.JetBrainsMono
import com.revrank.presentation.theme.Phosphor
import com.revrank.presentation.theme.RevRankTypography
import com.revrank.presentation.theme.TextSecondary
import com.revrank.presentation.theme.Void
import com.revrank.presentation.viewmodel.auth.AuthViewModel

@Composable
fun SignInScreen(
    onAuthenticated: () -> Unit,
    authViewModel: AuthViewModel = hiltViewModel()
) {
    val context = LocalContext.current
    val state by authViewModel.state.collectAsState()

    // Google Sign-In client requesting an ID token for the Firebase Web client.
    // default_web_client_id is generated by the google-services plugin from the
    // type-3 OAuth client in google-services.json.
    val googleClient = remember {
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(context.getString(R.string.default_web_client_id))
            .requestEmail()
            .build()
        GoogleSignIn.getClient(context, gso)
    }

    val launcher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.StartActivityForResult()
    ) { result ->
        val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
        try {
            val account = task.getResult(ApiException::class.java)
            val idToken = account.idToken
            if (idToken != null) {
                authViewModel.signInWithGoogle(idToken)
            } else {
                authViewModel.onError("No ID token returned")
            }
        } catch (e: ApiException) {
            authViewModel.onError("Google sign-in failed (${e.statusCode})")
        }
    }

    LaunchedEffect(state) {
        if (state is AuthViewModel.AuthUiState.Success) {
            authViewModel.reset()
            onAuthenticated()
        }
    }

    val loading = state is AuthViewModel.AuthUiState.Loading

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Void)
            .padding(horizontal = 32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        // Terminal chrome tag
        Text(
            text = "> REVRANK // SIGN_IN",
            style = RevRankTypography.labelSmall,
            color = Phosphor.copy(alpha = 0.55f)
        )
        Spacer(modifier = Modifier.height(40.dp))

        // Logo — Orbitron display with phosphor glow
        Text(
            text = "REVRANK",
            style = RevRankTypography.displayMedium,
            color = Phosphor
        )
        Spacer(modifier = Modifier.height(12.dp))
        Text(
            text = "YOUR RIDE HAS A SCORE",
            style = RevRankTypography.labelMedium,
            color = TextSecondary,
            textAlign = TextAlign.Center
        )

        Spacer(modifier = Modifier.height(56.dp))

        RevRankButton(
            text = if (loading) "Signing in..." else "Sign in with Google",
            onClick = {
                authViewModel.reset()
                launcher.launch(googleClient.signInIntent)
            },
            primary = true,
            enabled = !loading
        )
        Spacer(modifier = Modifier.height(14.dp))
        RevRankButton(
            text = "Sign in with Apple",
            onClick = { /* not supported on Android yet */ },
            enabled = false
        )

        val error = state as? AuthViewModel.AuthUiState.Error
        if (error != null) {
            Spacer(modifier = Modifier.height(16.dp))
            Text(
                text = error.message,
                fontFamily = JetBrainsMono,
                fontSize = 11.sp,
                color = Danger,
                textAlign = TextAlign.Center
            )
        }

        Spacer(modifier = Modifier.height(32.dp))
        Text(
            text = "By continuing you agree to the Terms & Privacy Policy",
            fontFamily = JetBrainsMono,
            fontSize = 10.sp,
            color = TextSecondary.copy(alpha = 0.6f),
            textAlign = TextAlign.Center
        )
    }
}
